# Generated by Django 5.2 on 2025-04-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_id_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_intent_id',
        ),
    ]
