# Generated by Django 5.2 on 2025-04-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
